### Navie bayes

> predicts the classes based on prababilistic value ..


> bayes therom -> conditional probability ..


> Navie -> I/p features are independent ..

<img src ="https://i.ytimg.com/vi/GfCtcNEUjs4/mqdefault.jpg">

In [121]:
import pandas as pd
import numpy as np

In [122]:
columns1=['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym', 'fM3Long', 'fM3Trans', 'fAlpha', 'fDist', 'class']

In [123]:
len(columns)

11

In [124]:
df =  pd.read_csv("/content/magic04.data",names=columns1)
df.tail()

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
19015,21.3846,10.9170,2.6161,0.5857,0.3934,15.2618,11.5245,2.8766,2.4229,106.8258,h
19016,28.9452,6.7020,2.2672,0.5351,0.2784,37.0816,13.1853,-2.9632,86.7975,247.4560,h
19017,75.4455,47.5305,3.4483,0.1417,0.0549,-9.3561,41.0562,-9.4662,30.2987,256.5166,h
19018,120.5135,76.9018,3.9939,0.0944,0.0683,5.8043,-93.5224,-63.8389,84.6874,408.3166,h
19019,187.1814,53.0014,3.2093,0.2876,0.1539,-167.3125,-168.4558,31.4755,52.7310,272.3174,h

In [125]:
#### Adding column names ..

In [126]:
 df.shape

(19020, 11)

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19020 entries, 0 to 19019
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   fLength   19020 non-null  float64
 1   fWidth    19020 non-null  float64
 2   fSize     19020 non-null  float64
 3   fConc     19020 non-null  float64
 4   fConc1    19020 non-null  float64
 5   fAsym     19020 non-null  float64
 6   fM3Long   19020 non-null  float64
 7   fM3Trans  19020 non-null  float64
 8   fAlpha    19020 non-null  float64
 9   fDist     19020 non-null  float64
 10  class     19020 non-null  object
dtypes: float64(10), object(1)
memory usage: 1.6+ MB

In [128]:
### g->1, h->0
df['class']=(df['class']=='g').astype(int)

In [129]:
df['class']

0        1
1        1
2        1
3        1
4        1
        ..
19015    0
19016    0
19017    0
19018    0
19019    0
Name: class, Length: 19020, dtype: int64

In [130]:
x=df [df.columns[:-1]]

In [131]:
df['class'].values

array([1, 1, 1, ..., 0, 0, 0])

In [132]:
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler

In [133]:
train, valid, test = np.split(df.sample(frac=1), [int(0.6*len(df)), int(0.8*len(df))])

/usr/local/lib/python3.13/dist-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [134]:
len(train)

11412

In [135]:
len(valid)

3804

In [136]:
len(test)

3804

In [137]:
def scale_dataset(dataframe, oversample=False):
  X = dataframe[dataframe.columns[:-1]].values#input
  y = dataframe[dataframe.columns[-1]].values#output

  scaler = StandardScaler()
  X = scaler.fit_transform(X) # its scaled input

  if oversample:
    ros = RandomOverSampler()
    X, y = ros.fit_resample(X, y)

  data = np.hstack((X, np.reshape(y, (-1, 1))))

  return data, X, y

In [138]:
train, X_train, y_train = scale_dataset(train, oversample=True)
valid, X_valid, y_valid = scale_dataset(valid, oversample=False)
test, X_test, y_test = scale_dataset(test, oversample=False)

> done with data preparation (standradization and balancing)

In [144]:
from sklearn.naive_bayes import GaussianNB

In [147]:
from sklearn.metrics import classification_report

In [148]:
nb = GaussianNB()

In [150]:
# train the model
nb.fit(X_train,y_train)

GaussianNB()

In [152]:
nbpredict = nb.predict(X_test)
nbpredict

array([1, 1, 1, ..., 1, 1, 1])

In [157]:
pd.DataFrame(train)

,0,1,2,3,4,5,6,7,8,9,10
0,2.067226,2.476010,0.685720,-0.868858,-0.908708,1.619287,2.859745,1.736575,0.804004,-0.506019,0.0
1,-0.453629,-0.383809,-0.187487,-0.312823,-0.438086,0.078205,-0.420793,-0.329754,-0.477925,-0.822731,1.0
2,-0.765660,-0.824852,-1.711912,1.827004,1.283590,0.475405,-0.012118,0.272929,-0.797632,-1.222718,1.0
3,-0.262168,-0.177736,0.156711,-0.445632,-0.548927,0.589350,0.478705,0.728812,-0.904467,0.066537,1.0
4,-0.634760,-0.235181,-0.716282,-0.161277,-0.281818,0.686853,0.065290,-0.588326,1.088740,-0.379716,1.0
...,...,...,...,...,...,...,...,...,...,...,...
14797,2.028908,0.442950,0.460314,-1.241385,-1.228512,-3.731926,1.742380,-1.283312,-0.704204,0.912198,0.0
14798,-0.504402,-0.016150,-0.615651,0.180941,-0.091934,0.836692,0.109539,-0.662724,1.732632,-0.383954,0.0
14799,0.063137,-0.348842,-0.170608,0.055847,-0.029245,0.591053,0.488040,0.793020,-0.375138,0.729455,0.0
14800,0.010340,-0.712279,-0.195606,0.109852,0.037987,0.493567,0.507695,-0.488419,1.542970,-1.912299,0.0
14801,-0.648028,-0.484196,-0.773755,0.550713,0.607639,0.260448,0.090660,-0.463118,-0.277312,-0.608572,0.0

In [158]:
pd.DataFrame(train)[10].value_counts()

10
0.0    7401
1.0    7401
Name: count, dtype: int64

In [154]:
### evaluating model
print(classification_report(y_test,nbpredict))

              precision    recall  f1-score   support

           0       0.67      0.41      0.51      1307
           1       0.74      0.90      0.81      2497

    accuracy                           0.73      3804
   macro avg       0.71      0.65      0.66      3804
weighted avg       0.72      0.73      0.71      3804

##### KNN

In [166]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [167]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [177]:
kpedict = knn.predict(X_test)

In [182]:
print(classification_report(y_test,kpedict))

              precision    recall  f1-score   support

           0       0.73      0.72      0.72      1307
           1       0.85      0.86      0.86      2497

    accuracy                           0.81      3804
   macro avg       0.79      0.79      0.79      3804
weighted avg       0.81      0.81      0.81      3804

In [184]:
print(classification_report(y_test,kpedict))

              precision    recall  f1-score   support

           0       0.73      0.72      0.72      1307
           1       0.85      0.86      0.86      2497

    accuracy                           0.81      3804
   macro avg       0.79      0.79      0.79      3804
weighted avg       0.81      0.81      0.81      3804

In [140]:
train

array([[ 2.06722593,  2.47600986,  0.68571963, ...,  0.80400406,
        -0.50601915,  0.        ],
       [-0.45362945, -0.38380892, -0.18748677, ..., -0.47792456,
        -0.82273093,  1.        ],
       [-0.76565954, -0.82485169, -1.71191242, ..., -0.79763165,
        -1.2227179 ,  1.        ],
       ...,
       [ 0.06313717, -0.34884161, -0.17060806, ..., -0.37513832,
         0.72945498,  0.        ],
       [ 0.01033995, -0.71227861, -0.19560565, ...,  1.54297029,
        -1.91229948,  0.        ],
       [-0.64802759, -0.48419642, -0.77375502, ..., -0.27731247,
        -0.60857165,  0.        ]])